using System;
using System.Windows.Forms;

namespace Reversi
{
    public partial class ReversiKataRunner : Form
    {
        public ReversiKataRunner()
        {
            InitializeComponent();
        }

        private void sample1Button_Click(object sender, EventArgs e)
        {
            inputTextBox.Text =
@"........
........
........
...BW...
...WB...
........
........
........
B";
        }

        private void sample2Button_Click(object sender, EventArgs e)
        {
            inputTextBox.Text =
@"........
........
...W....
..BBBB..
...WB...
........
........
........
W";
        }

        private void sample3Button_Click(object sender, EventArgs e)
        {
            inputTextBox.Text =
@"........
........
....WW..
..BBWW..
...BB...
...WBB..
........
........
B";
        }

        private void runButton_Click(object sender, EventArgs e)
        {
            outputTextBox.Text = Reversi.Run(inputTextBox.Text);
        }
    }
}
